development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: natalyapatrikeeva
  password: v22a11l76o

test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: natalyapatrikeeva
  password: v22a11l76o
